// <auto-generated />
namespace Rosneft.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _initial5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_initial5));
        
        string IMigrationMetadata.Id
        {
            get { return "202303120940140__initial5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
